### ISSUE TITLE
Several issues with inquiry form.

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#16]
On the dev site, the "Inquiry for" field disappeared from the form somehow. On the live site, because it is now a multi-valued field, the field is there, but styling doesn't match any longer. Can you please 
1) check why it is not there on dev and 
2) adapt the styling so it looks like before (hide button and second field, drag handler and background colour)? 
3) Also, even on the German page, the translation for Inquiry for (Anfrage für) is not shown, although it exists.

**Comment by darshi-shah** [comment]
Hi Rainer,

Please do following : 

1 - take pull

2 - Go to admin/structure/crm-core/profile/manage/call/edit and Select "CRM Core Activity" 

3 - For "CRM Core Activity Type" select "Anfrange"

4 - check "inquiry for" and "notes" under "CRM Core Activity Fields"

5 - Move "inquiry for" to top of all fields shown in drag and drop below this and save

6 - clear cache

Let me know any questions in this. I am checking for translation.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,

I found out what happened with anfrage and call... I would call that a bug. I duplicated the call profile from the anfrage profile, but didn't create a page or block on the settings page, because we don't need one for that type. So the duplicated profile had the same path (/anfrage), and instead of creating an anfrage, a call was created... I had to create a path and block for call, then save it and delete page and block again in order to change the path (that was only visible in the export).

After I did that and the above steps, the inquiry for field showed again... Thanks for pointing me in the right direction by mentioning call profile ;-)

So now there's only the translation and styling left.

**Comment by darshi-shah** [comment]
Hi Rainer,

CSS is already pushed. I checked translations. Its enable but string is not list of translations.  I am checking this. I will let you know once done.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,

ah ok, I forgot to do another compass watch... I added the rest of the css to hide the unwanted stuff from the multi-form field now and pushed it. 

If I search for "Inquiry for" (Case Sensitive!), I get two strings, but their translations are available in German. So no idea why they don't show while the other form elements do...

**Comment by darshi-shah** [comment]
Hi Rainer,

I added string via code to make it available for translation. Please take pull and then go to "admin/config/regional/translate/translate" , new string will be available here. Make sure cache is cleared and strings are refreshed.

Let me know any question in this.

Thanks 
Darshi

**Comment by heliogabal** [comment]
I pulled, cleared cache, refreshed strings, but I still can't see another string "Inquiry for", just the two instances that were already there. Weird, but I'll check again tomorrow when I had more sleep...

**Comment by darshi-shah** [comment]
Hi Rainer,

Please delete existing strings. To make new string available for translation,  visit page that has this string. In our case, inquiry form.  You will see string in english.  Refresh the strings after this and clear cache. New string will be available for translation.

Let  me know  any questions in this. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,

deleted existing, refreshed, cleared cache, translated new string, but I still can't get it to show in German on the inquiry form. Does this work locally for you? No idea what I'm doing wrong here...

**Comment by darshi-shah** [comment]
Hi Rainer,

This is working on local for me. I have tested this in 2 different systems. Please see attached screenshot.

Thanks
Darshi
![screenshot from 2016-05-20 16_56_12](https://cloud.githubusercontent.com/assets/15724372/15426973/8a728e46-1eaf-11e6-839f-61eb5bfbf7ae.png)

**Comment by heliogabal** [comment]
Hi Darshi, 

hm, no idea why this isn't working for me. I'll test once more tomorrow, otherwise it might be best to close this and hope that if will be visible on live...

**Comment by heliogabal** [comment]
There is still this freaking problem with the translation for Inquiry (Lightbox title) and the inquiry for field... don't know why that is happening only on live ;-( I deleted all existing strings with Inquiry, visited the form in the lightbox and in a new tab to make sure the string gets registered by Drupal, refreshed strings, cleared cache, but whatever I do, I can't see the string Inquiry or Inquiry for to translate it. I'll attach two screens to show what it looks like. Curiously, when I open the form in a new tab, the Title is translated...
![inquiry_lightbox](https://cloud.githubusercontent.com/assets/389844/18639524/8a685d46-7e94-11e6-97a0-510a91132e74.png)
![inquiry_new_tab](https://cloud.githubusercontent.com/assets/389844/18639530/8e5da398-7e94-11e6-9e0a-a8dfadc21449.png)

Hopefully, that gives you any idea of the cause for this mistery...

**Comment by darshi-shah** [comment]
Hi Rainer,

This is fixed and pushed on dev. Please revert hk_ct feature.

Thanks

**Comment by heliogabal** [comment]
I still can't see the translated title for the "Inquiry for" field. But you know what? Why don't you just get rid of it and don't show the title. It seems obvious what it is anyway. So we can finally close this as well.

**Comment by darshi-shah** [comment]
Hi Rainer,

Please revert hk_translation and make sure that Features Translations module is enabled. The title will be available for translation.

Thanks,
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
I reverted hk_translation and cleared cache and features_translations is enabled. The title is available for translation and translated, I still don't see the translation on the lightbox form.

I even found this issue (https://www.drupal.org/node/2698381) and tried with the applied patch, that at least led me to have the features in standard status. But I still don't see the title translated...

**Comment by darshi-shah** [comment]
Hi Rainer,

You need field translation enabled as well.  Once you enable it, you will see 3 strings for translate. Please see screenshot : http://i.share.pho.to/6a0e3f19_o.png

Sorry about module name  mix up.

Thanks
Darshi

**Comment by heliogabal** [comment]
Yay, finally! How could that have been missed? Why do you have that field_translation module disabled and you have it enabled? How could we have missed that? Once I enabled it, the Inquiry for translation finally shows up on the form. Hope that most of the other strange discrepancies with the translation have been caused by this as well...
