### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by darshi-shah** [saurabhd/hk_realestate#33]
Apart from Gdoc sheet shared, below are the additional issues : 

~~\- logo not clickable to go to frontpage~~
~~\- search box visible on first load (mobile), should be hidden initially, and toggle on search icon click~~
~~\- search box not correctly toggling on search icon click (the empty search box is still shown)~~
~~\- AGB should be 1 column on mobile~~
~~keyboard opens on select active~~  
- contact form address too wide on mobile (portrait mode)
- button hidden when keyboard active on mobile (on inquiry form lightbox)

~~anfahrt hide language selector (en/de on top of map)~~
~~floor plan too big on mobile and tablet, so it jumps to second row~~
~~Footer (Frontpage): missing on tablet and desktop, overlapping scale and credits on mobile portrait, not on bottom of screen on landscape~~
~~we don't need the map zoom indicator on the frontpage~~

**Comment by heliogabal** [comment]
There are some things fixed, but three issues remaining.

**Comment by darshi-shah** [comment]
Hi Rainer,

Can you please explain below points ? I am checking them on dev site.
- button hidden when keyboard active on mobile (on inquiry form lightbox)
- anfahrt hide language selector (en/de on top of map)

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,
- when you try to fill out the inquiry, everything seems to be fine at first. But as soon as you open the keyboard to fill out the message field, the inquiry button is not reachable any longer, so the form can't be sent. And I don't know myself how to hide the keyboard again on my android, so probably others will have this problem as well.
- I don't know where it comes from, but on the page on top of the map, there is a language selector to switch the map to another language. We don't need that, as we can switch the whole page with our language selector. 

Clearer now?

**Comment by darshi-shah** [comment]
Hi Rainer,

Thanks for explaining. This is fixed and pushed on develop branch. Please take pull. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
~~\- contact form address too wide on mobile (portrait mode)
this is still happening on my 320px android. The country select is too wide, so the whole fieldset gets pushed over the page bg.~~
- button hidden when keyboard active on mobile (on inquiry form lightbox)
  also still a problem for me.

I did feature revert and cache clear several times...

**Comment by darshi-shah** [comment]
These changes are pushed on develop branch. Please take pull.
